# Use the official Python image from the Docker Hub
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/myapp

# Copy the current directory contents into the container at /usr/src/myapp
COPY . /usr/src/myapp/

# Install any dependencies specified in requirements.txt


# Run the main.py script when the container starts
CMD ["python", "main.py"]
